-- Generated by `prisma migrate diff` (pickup: pnpm supabase:migration:diff -- add_cilo_mapping_manifestation)
-- Reviewed and trimmed to this slice's changes. The generated diff also
-- contained pre-existing drift between the demo database and the Prisma
-- datamodel (index renames, FK/reference reconciliation on other tables,
-- TIMESTAMP normalization). None of it belongs to slice #451, so it is
-- intentionally excluded. The unique pair index
-- (cilo_mappings_cilo_id_go_id_key) and the SQL-only trigger
-- cilo_mappings_scope_check are untouched by this migration.

-- CreateEnum
CREATE TYPE "CILOMappingManifestation" AS ENUM ('LEARNING', 'PRACTICE', 'OPPORTUNITY');

-- AlterTable
ALTER TABLE "cilo_mappings" ADD COLUMN "manifestation" "CILOMappingManifestation",
ADD COLUMN "updated_at" TIMESTAMP(3);